name: Open Source License Scanning

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci  # 'npm ci' is faster and more reliable for CI/CD

      - name: Run License Compliance Scan
        # This will fail the build automatically if Exit Code 1 is returned
        run: npm run license-compliance